FROM python:3.10

EXPOSE 8501

WORKDIR /app

COPY requirements.txt /tmp/

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --requirement /tmp/requirements.txt

COPY . .

CMD ["streamlit", "run", "app/streamlitapp.py"]